print("Empty string:", bool(""))
print("Text:", bool("Python"))
print("Zero:", bool(0))
print("Nonzero:", bool(-3))
print("None:", bool(None))
print("Empty list:", bool([]))
print("Filled list:", bool(["python"]))
print("Empty dictionary:", bool({}))
print("Filled dictionary:", bool({"topic": "python"}))
print("Empty set:", bool(set()))
print("Filled set:", bool({"python"}))
